name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu:18.04
    steps:
    - uses: actions/checkout@v3
    - name ver
      run ls -l
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s) 

