FROM sistemasoperativostur/netoslab-router:latest
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
# HTTP service 
RUN apt update \
    && apt install -y \
       apache2 \
    && apt clean \
    && apt -y autoremove \
    && rm -rf /var/lib/apt/lists/*
COPY resources/ejemplo.mp3 /root
CMD ["/bin/bash"]
