FROM sistemasoperativostur/netoslab-router:latest
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
# squid service
RUN apt update \
    && apt install -y \
       squid \
    && apt clean \
    && apt -y autoremove \
    && rm -rf /var/lib/apt/lists/*
COPY resources/nsswitch.conf /etc/nsswitch.conf
CMD ["/bin/bash"]
