FROM debian:stable-slim AS updates
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
RUN apt update
RUN apt install -y iproute2 net-tools telnet netcat-traditional iptables tcpdump rsyslog ethtool tcpdump iputils-ping openssh-server openssh-client nano less kea

#set root pass
RUN echo root:netOSLab | chpasswd
RUN apt autoremove



## dhcp
#apt install isc-dhcp-server
#apt install isc-dhcp-relay
## dns
#apt install bind9
#en /etc/bind/named.conf.options modificado -> 1.3
    #listen-on { 127.0.0.1; };
    #listen-on-v6 { ::1; };
#apt install bind9-host
##http
#apt install apache2
#copiar un archivo mp3 ...luego lo usara squid
##smtp
#apt install sendmail
#apt install mutt
#agregar dos lineas a /etc/mail/sendmail.mc -> 1.3
    #FEATURE(accept_unqualified_senders)dnl
    #FEATURE(accept_unresolvable_domains)dnl
#sacar ultima linea en /etc/mail/local-host-names -> 1.3
#apt install dovecot-pop3d
#en el archivo /etc/dovecot/conf.d/10-auth.conf
    #disable_plaintext_auth = no
##vpn
#apt install openvpn   
#copiar todos los directorios de la version anterior a /usr/share/doc/openvpn/examples
#deszipear /usr/share/doc/openvpn/examples/sample-keys/server.crt.gz
#deszipear /usr/share/doc/openvpn/examples/sample-keys/client.crt.gz
#deszipear /usr/share/doc/openvpn/examples/sample-config-files/server.conf.gz
##proxy
#apt install squid
#sacar la palabra dns en el archivo /etc/nsswitch.conf -> 1.3
##samba se corre en lpr
RUN apt autoremove
