FROM debian:stable-slim
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
RUN apt update &&  apt install -y \
  iproute2 \
  net-tools \
  telnet \
  netcat-traditional \
  iptables \
  tcpdump \
  rsyslog \
  ethtool \
  tcpdump \
  iputils-ping \
  vim \
  nano \
  less \
  openssh-server \
  openssh-client 
#set root pass
RUN echo root:netOSLab | chpasswd
#service 
RUN apt install -y \
  sendmail \
  mutt \
  dovecot-pop3d \
  && rm -rf /var/lib/apt/lists/*
#COPY resources/sendmail.mc /etc/mail/sendmail.mc
# FEATURE(accept_unqualified_senders)dnl
# FEATURE(accept_unresolvable_domains)dnl
#COPY resources/local-host-names /etc/mail/local-host-names
# saca la ultima linea
#COPY resources/10-auth.conf  /etc/dovecot/conf.d/10-auth.conf
# disable_plaintext_auth = no
RUN apt -y autoremove

