FROM sistemasoperativostur/netoslab-router:latest
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
#Firewall service - only apache2 to test traffic filters
RUN apt update \
    && apt install -y \
       apache2 \
    && apt clean \
    && apt -y autoremove \
    && rm -rf /var/lib/apt/lists/*
CMD ["/bin/bash"]
