FROM sistemasoperativostur/netoslab-router:latest
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
#NDS service 
RUN apt update \
    && apt install -y \
       bind9 \
       bind9-host \
    && apt clean \
    && apt -y autoremove \
    && rm -rf /var/lib/apt/lists/*
COPY resources/named.conf.options /etc/bind/named.conf.options
#en /etc/bind/named.conf.options modificado 
    #listen-on { 127.0.0.1; };
    #listen-on-v6 { ::1; };
CMD ["/bin/bash"]

