FROM sistemasoperativostur/netoslab-router:latest
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
#openvpn service
RUN apt update \
    && apt install -y \
       openvpn \
    && apt clean \
    && apt -y autoremove \
    && rm -rf /var/lib/apt/lists/*
COPY resources/sample-config-files/* /etc/openvpn
COPY resources/sample-keys/* /etc/openvpn
CMD ["/bin/bash"]
