FROM sistemasoperativostur/netoslab-router:latest
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
# SMB service 
RUN apt update \
    && apt install -y \
       samba \
       samba-common-bin \
    && apt clean \
    && apt -y autoremove \
    && rm -rf /var/lib/apt/lists/*
CMD ["/bin/bash"]
