FROM debian:stable-slim AS updates
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
RUN apt update
RUN apt install -y iproute2 net-tools telnet netcat iptables tcpdump iputils-ping openssh-client nano less

#set root pass
RUN echo root:netOSLab | chpasswd
RUN apt autoremove
