FROM debian:stable-slim AS updates
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
RUN apt update && \
    apt install -y \
      iproute2 \
      net-tools \
      telnet \
      netcat-traditional \
      iptables \
      tcpdump \
      ethtool \
      rsyslog \
      iputils-ping \
      vim \
      nano \
      less \
      openssh-server \
      openssh-client \
    && apt clean \
    && apt -y autoremove \
    && rm -rf /var/lib/apt/lists/* \
    && echo root:netOSLab | chpasswd #set root pass
CMD ["/bin/bash"]

# Difference between CMD and ENTRYPOINT
#$ docker inspect -f '{{.Config.Entrypoint}}'  python:latest
#[]
#$ docker inspect -f '{{.Config.Cmd}}'  python:latest
#[python3]
#$ docker run -it --rm --entrypoint python3 python:latest
#Python 3.13.1 (main, Jan 14 2025, 05:25:12) [GCC 12.2.0] on linux
#Type "help", "copyright", "credits" or "license" for more information.
#>>>
#$ docker run -it --rm --entrypoint python3 python:latest "--version"
#Python 3.13.1
#$
