FROM sistemasoperativostur/netoslab-router:latest
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
#SMTP service
RUN apt update \
    && apt install -y \
       sendmail \
       mutt \
       dovecot-pop3d \
    && apt clean \
    && apt -y autoremove \
    && rm -rf /var/lib/apt/lists/*
COPY resources/sendmail.mc /etc/mail/sendmail.mc
# FEATURE(accept_unqualified_senders)dnl
# FEATURE(accept_unresolvable_domains)dnl
COPY resources/local-host-names /etc/mail/local-host-names
# saca la ultima linea
COPY resources/10-auth.conf  /etc/dovecot/conf.d/10-auth.conf
# disable_plaintext_auth = no
CMD ["/bin/bash"]
