FROM debian:stable-slim
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
RUN apt update &&  apt install -y \
  iproute2 \
  net-tools \
  telnet \
  netcat-traditional \
  iptables \
  tcpdump \
  rsyslog \
  ethtool \
  tcpdump \
  iputils-ping \
  vim \
  nano \
  less \
  openssh-server \
  openssh-client 
#set root pass
RUN echo root:netOSLab | chpasswd
#service 
RUN apt install -y \
  openvpn \
  && rm -rf /var/lib/apt/lists/*
#COPY resources/named.conf.options /etc/bind/named.conf.options
COPY resources/sample-config-files/server.conf /etc/openvpn
COPY resources/sample-config-files/client.conf /etc/openvpn
COPY resources/sample-keys/ca.crt /etc/openvpn
COPY resources/sample-keys/ta.key /etc/openvpn
COPY resources/sample-keys/server.crt /etc/openvpn
COPY resources/sample-keys/server.key /etc/openvpn
COPY resources/sample-keys/client.crt /etc/openvpn
COPY resources/sample-keys/client.key /etc/openvpn
COPY resources/sample-keys/dh2048.pem /etc/openvpn
RUN apt -y autoremove

