FROM debian:stable-slim
LABEL mantainer=”ctaffer@unsl.edu.ar”
WORKDIR /root
RUN apt update &&  apt install -y \
  iproute2 \
  net-tools \
  telnet \
  netcat-traditional \
  iptables \
  tcpdump \
  rsyslog \
  ethtool \
  tcpdump \
  iputils-ping \
  vim \
  nano \
  less \
  openssh-server \
  openssh-client 
#set root pass
RUN echo root:netOSLab | chpasswd
#service 
RUN apt install -y \
  squid \
  && rm -rf /var/lib/apt/lists/*
COPY resources/nsswitch.conf /etc/nsswitch.conf
RUN apt -y autoremove
