#create a github action to build and push the server-squid docker image to the docker hub 
name: Squid Server Docker Image Build CI
on:
  push:
#    branches:
#    - master
    paths:
      - 'Dockerfile-servidor-squid'
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: netoslab-servidor-squid
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Get tag # latest or date of the build
      id: tag
      run: |
        if [ $GITHUB_REF == 'refs/heads/master' ] ; then 
          echo "version=latest">> $GITHUB_OUTPUT
        else
          echo "version=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT
        fi
    - name: Build HTTP Server Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile-servidor-squid --tag $DOCKER_USER/$REPO_NAME:${{ steps.tag.outputs.version }}
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.tag.outputs.version }}

